/**
 * Lista de Raças disponíveis em Tormenta 20
 */
export const RACES = [
  { id: 'humano', name: 'Humano', bonus: { any: 2 } },
  { id: 'anao', name: 'Anão', bonus: { constituicao: 2 }, penalty: { destreza: -1 } },
  { id: 'elfo', name: 'Elfo', bonus: { destreza: 2 }, penalty: { constituicao: -1 } },
  { id: 'goblin', name: 'Goblin', bonus: { destreza: 2 }, penalty: { carisma: -1 } },
  { id: 'lefou', name: 'Lefou', bonus: { inteligencia: 1, sabedoria: 1 } },
  { id: 'minotauro', name: 'Minotauro', bonus: { forca: 2 }, penalty: { sabedoria: -1 } },
  { id: 'qareen', name: 'Qareen', bonus: { carisma: 2 }, penalty: { sabedoria: -1 } },
  { id: 'golem', name: 'Golem', bonus: { forca: 2 }, penalty: { carisma: -1 } },
  { id: 'hynne', name: 'Hynne', bonus: { destreza: 1, carisma: 1 } },
  { id: 'kliren', name: 'Kliren', bonus: { inteligencia: 2 }, penalty: { forca: -1 } },
  { id: 'medusa', name: 'Medusa', bonus: { destreza: 1, carisma: 1 } },
  { id: 'osteon', name: 'Osteon', bonus: { constituicao: 1, sabedoria: 1 } },
  { id: 'sereia', name: 'Sereia/Tritão', bonus: { carisma: 2 }, penalty: { forca: -1 } },
  { id: 'trog', name: 'Trog', bonus: { constituicao: 2 }, penalty: { inteligencia: -1 } },
  { id: 'aggelus', name: 'Aggelus', bonus: { sabedoria: 2, carisma: 1 } },
  { id: 'sulfure', name: 'Sulfure', bonus: { destreza: 1, inteligencia: 2 } },
];

/**
 * Lista de Classes disponíveis em Tormenta 20 com estatísticas completas de PV/PM, perícias e proficiências.
 * hp.initial aplica-se ao 1º nível (valor base + Constituição) e hp.perLevel aos níveis subsequentes.
 */

export const CLASSES = [
  {
    id: 'arcanista',
    name: 'Arcanista',
    hitDie: 6,
    mainAttr: 'inteligencia',
    hp: { initial: 8, perLevel: 2 },
    mpPerLevel: 6,
    skillTraining: {
      mandatory: ['misticismo', 'vontade'],
      choiceGroups: [
        {
          choose: 2,
          options: [
            'conhecimento',
            'diplomacia',
            'enganacao',
            'guerra',
            'iniciativa',
            'intimidacao',
            'intuicao',
            'investigacao',
            'nobreza',
            'oficio',
            'percepcao',
          ],
        },
      ],
    },
    proficiencies: [],
  },
  {
    id: 'barbaro',
    name: 'Bárbaro',
    hitDie: 12,
    mainAttr: 'forca',
    hp: { initial: 24, perLevel: 6 },
    mpPerLevel: 3,
    skillTraining: {
      mandatory: ['fortitude', 'luta'],
      choiceGroups: [
        {
          choose: 4,
          options: [
            'adestramento',
            'atletismo',
            'cavalgar',
            'iniciativa',
            'intimidacao',
            'oficio',
            'percepcao',
            'pontaria',
            'sobrevivencia',
            'vontade',
          ],
        },
      ],
    },
    proficiencies: ['armas marciais', 'escudos'],
  },
  {
    id: 'bardo',
    name: 'Bardo',
    hitDie: 8,
    mainAttr: 'carisma',
    hp: { initial: 12, perLevel: 3 },
    mpPerLevel: 4,
    skillTraining: {
      mandatory: ['atuacao', 'reflexos'],
      choiceGroups: [
        {
          choose: 6,
          options: [
            'acrobacia',
            'cavalgar',
            'conhecimento',
            'diplomacia',
            'enganacao',
            'furtividade',
            'iniciativa',
            'intuicao',
            'investigacao',
            'jogatina',
            'ladinagem',
            'luta',
            'misticismo',
            'nobreza',
            'percepcao',
            'pontaria',
            'vontade',
          ],
        },
      ],
    },
    proficiencies: ['armas marciais'],
  },
  {
    id: 'bucaneiro',
    name: 'Bucaneiro',
    hitDie: 10,
    mainAttr: 'destreza',
    hp: { initial: 16, perLevel: 4 },
    mpPerLevel: 3,
    skillTraining: {
      mandatory: ['reflexos'],
      choiceGroups: [
        { choose: 1, options: ['luta', 'pontaria'] },
        {
          choose: 4,
          options: [
            'acrobacia',
            'atletismo',
            'atuacao',
            'enganacao',
            'fortitude',
            'furtividade',
            'iniciativa',
            'intimidacao',
            'jogatina',
            'luta',
            'oficio',
            'percepcao',
            'pilotagem',
            'pontaria',
          ],
        },
      ],
    },
    proficiencies: ['armas marciais'],
  },
  {
    id: 'cacador',
    name: 'Caçador',
    hitDie: 10,
    mainAttr: 'destreza',
    hp: { initial: 16, perLevel: 4 },
    mpPerLevel: 4,
    skillTraining: {
      mandatory: ['sobrevivencia'],
      choiceGroups: [
        { choose: 1, options: ['luta', 'pontaria'] },
        {
          choose: 6,
          options: [
            'adestramento',
            'atletismo',
            'cavalgar',
            'cura',
            'fortitude',
            'furtividade',
            'iniciativa',
            'investigacao',
            'luta',
            'oficio',
            'percepcao',
            'pontaria',
            'reflexos',
          ],
        },
      ],
    },
    proficiencies: ['armas marciais', 'escudos'],
  },
  {
    id: 'cavaleiro',
    name: 'Cavaleiro',
    hitDie: 10,
    mainAttr: 'forca',
    hp: { initial: 20, perLevel: 5 },
    mpPerLevel: 3,
    skillTraining: {
      mandatory: ['fortitude', 'luta'],
      choiceGroups: [
        {
          choose: 2,
          options: [
            'adestramento',
            'atletismo',
            'cavalgar',
            'diplomacia',
            'guerra',
            'iniciativa',
            'intimidacao',
            'nobreza',
            'percepcao',
            'vontade',
          ],
        },
      ],
    },
    proficiencies: ['armas marciais', 'armaduras pesadas', 'escudos'],
  },
  {
    id: 'clerigo',
    name: 'Clérigo',
    hitDie: 8,
    mainAttr: 'sabedoria',
    hp: { initial: 16, perLevel: 4 },
    mpPerLevel: 5,
    skillTraining: {
      mandatory: ['religiao', 'vontade'],
      choiceGroups: [
        {
          choose: 2,
          options: [
            'conhecimento',
            'cura',
            'diplomacia',
            'fortitude',
            'iniciativa',
            'intuicao',
            'luta',
            'misticismo',
            'nobreza',
            'oficio',
            'percepcao',
          ],
        },
      ],
    },
    proficiencies: ['armaduras pesadas', 'escudos'],
  },
  {
    id: 'druida',
    name: 'Druida',
    hitDie: 8,
    mainAttr: 'sabedoria',
    hp: { initial: 16, perLevel: 4 },
    mpPerLevel: 4,
    skillTraining: {
      mandatory: ['sobrevivencia', 'vontade'],
      choiceGroups: [
        {
          choose: 4,
          options: [
            'adestramento',
            'atletismo',
            'cavalgar',
            'conhecimento',
            'cura',
            'fortitude',
            'iniciativa',
            'intuicao',
            'luta',
            'misticismo',
            'oficio',
            'percepcao',
            'religiao',
          ],
        },
      ],
    },
    proficiencies: ['escudos'],
  },
  {
    id: 'guerreiro',
    name: 'Guerreiro',
    hitDie: 10,
    mainAttr: 'forca',
    hp: { initial: 20, perLevel: 5 },
    mpPerLevel: 3,
    skillTraining: {
      mandatory: ['fortitude'],
      choiceGroups: [
        { choose: 1, options: ['luta', 'pontaria'] },
        {
          choose: 2,
          options: [
            'adestramento',
            'atletismo',
            'cavalgar',
            'guerra',
            'iniciativa',
            'intimidacao',
            'luta',
            'oficio',
            'percepcao',
            'pontaria',
            'reflexos',
          ],
        },
      ],
    },
    proficiencies: ['armas marciais', 'armaduras pesadas', 'escudos'],
  },
  {
    id: 'inventor',
    name: 'Inventor',
    hitDie: 8,
    mainAttr: 'inteligencia',
    hp: { initial: 12, perLevel: 3 },
    mpPerLevel: 4,
    skillTraining: {
      mandatory: ['oficio', 'vontade'],
      choiceGroups: [
        {
          choose: 4,
          options: [
            'conhecimento',
            'cura',
            'diplomacia',
            'fortitude',
            'iniciativa',
            'investigacao',
            'luta',
            'misticismo',
            'oficio',
            'pilotagem',
            'percepcao',
            'pontaria',
          ],
        },
      ],
    },
    proficiencies: [],
  },
  {
    id: 'ladino',
    name: 'Ladino',
    hitDie: 8,
    mainAttr: 'destreza',
    hp: { initial: 12, perLevel: 3 },
    mpPerLevel: 4,
    skillTraining: {
      mandatory: ['ladinagem', 'reflexos'],
      choiceGroups: [
        {
          choose: 8,
          options: [
            'acrobacia',
            'atletismo',
            'atuacao',
            'cavalgar',
            'conhecimento',
            'diplomacia',
            'enganacao',
            'furtividade',
            'iniciativa',
            'intimidacao',
            'intuicao',
            'investigacao',
            'jogatina',
            'luta',
            'oficio',
            'percepcao',
            'pilotagem',
            'pontaria',
          ],
        },
      ],
    },
    proficiencies: [],
  },
  {
    id: 'lutador',
    name: 'Lutador',
    hitDie: 10,
    mainAttr: 'destreza',
    hp: { initial: 20, perLevel: 5 },
    mpPerLevel: 3,
    skillTraining: {
      mandatory: ['fortitude', 'luta'],
      choiceGroups: [
        {
          choose: 4,
          options: [
            'acrobacia',
            'adestramento',
            'atletismo',
            'enganacao',
            'furtividade',
            'iniciativa',
            'intimidacao',
            'oficio',
            'percepcao',
            'pontaria',
            'reflexos',
          ],
        },
      ],
    },
    proficiencies: [],
  },
  {
    id: 'nobre',
    name: 'Nobre',
    hitDie: 8,
    mainAttr: 'carisma',
    hp: { initial: 16, perLevel: 4 },
    mpPerLevel: 4,
    skillTraining: {
      mandatory: ['vontade'],
      choiceGroups: [
        { choose: 1, options: ['diplomacia', 'intimidacao'] },
        {
          choose: 4,
          options: [
            'adestramento',
            'atuacao',
            'cavalgar',
            'conhecimento',
            'diplomacia',
            'enganacao',
            'fortitude',
            'guerra',
            'iniciativa',
            'intimidacao',
            'intuicao',
            'investigacao',
            'jogatina',
            'luta',
            'nobreza',
            'oficio',
            'percepcao',
            'pontaria',
          ],
        },
      ],
    },
    proficiencies: ['armas marciais', 'armaduras pesadas', 'escudos'],
  },
  {
    id: 'paladino',
    name: 'Paladino',
    hitDie: 10,
    mainAttr: 'carisma',
    hp: { initial: 20, perLevel: 5 },
    mpPerLevel: 3,
    skillTraining: {
      mandatory: ['luta', 'vontade'],
      choiceGroups: [
        {
          choose: 2,
          options: [
            'adestramento',
            'atletismo',
            'cavalgar',
            'cura',
            'diplomacia',
            'fortitude',
            'guerra',
            'iniciativa',
            'intuicao',
            'nobreza',
            'percepcao',
            'religiao',
          ],
        },
      ],
    },
    proficiencies: ['armas marciais', 'armaduras pesadas', 'escudos'],
  },
];

/**
 * Lista de Perícias
 */
export const SKILLS = [
  { id: 'acrobacia', name: 'Acrobacia', attr: 'destreza' },
  { id: 'adestramento', name: 'Adestramento', attr: 'carisma' },
  { id: 'atletismo', name: 'Atletismo', attr: 'forca' },
  { id: 'atuacao', name: 'Atuação', attr: 'carisma' },
  { id: 'cavalgar', name: 'Cavalgar', attr: 'destreza' },
  { id: 'conhecimento', name: 'Conhecimento', attr: 'inteligencia' },
  { id: 'cura', name: 'Cura', attr: 'sabedoria' },
  { id: 'diplomacia', name: 'Diplomacia', attr: 'carisma' },
  { id: 'enganacao', name: 'Enganação', attr: 'carisma' },
  { id: 'fortitude', name: 'Fortitude', attr: 'constituicao' },
  { id: 'furtividade', name: 'Furtividade', attr: 'destreza' },
  { id: 'guerra', name: 'Guerra', attr: 'inteligencia' },
  { id: 'iniciativa', name: 'Iniciativa', attr: 'destreza' },
  { id: 'intimidacao', name: 'Intimidação', attr: 'carisma' },
  { id: 'intuicao', name: 'Intuição', attr: 'sabedoria' },
  { id: 'investigacao', name: 'Investigação', attr: 'inteligencia' },
  { id: 'jogatina', name: 'Jogatina', attr: 'carisma' },
  { id: 'ladinagem', name: 'Ladinagem', attr: 'destreza' },
  { id: 'luta', name: 'Luta', attr: 'forca' },
  { id: 'misticismo', name: 'Misticismo', attr: 'inteligencia' },
  { id: 'nobreza', name: 'Nobreza', attr: 'inteligencia' },
  { id: 'oficio', name: 'Ofício', attr: 'inteligencia' },
  { id: 'percepcao', name: 'Percepção', attr: 'sabedoria' },
  { id: 'pilotagem', name: 'Pilotagem', attr: 'destreza' },
  { id: 'pontaria', name: 'Pontaria', attr: 'destreza' },
  { id: 'reflexos', name: 'Reflexos', attr: 'destreza' },
  { id: 'religiao', name: 'Religião', attr: 'sabedoria' },
  { id: 'sobrevivencia', name: 'Sobrevivência', attr: 'sabedoria' },
];

/**
 * Lista de Talentos (Poderes de Classe)
 * Estrutura: { id, name, description, prerequisites: [] }
 */
export const HABILIDADES = {
  cacador: [
    // Habilidades de Classe (Padrão)
    {
      id: 'marca_presa',
      name: 'Marca da Presa',
      type: 'Habilidade base',
      level: 1,
      description: 'Você pode gastar uma ação de movimento e 1 PM para analisar uma criatura em alcance curto. Até o fim da cena, você recebe +1d4 nas rolagens de dano contra essa criatura. A cada quatro níveis, você pode gastar +1 PM para aumentar o bônus de dano (veja a tabela da classe).',
      prerequisites: [],
    },
    {
      id: 'rastreador',
      name: 'Rastreador',
      type: 'Habilidade base',
      level: 1,
      description: 'Você recebe +2 em Sobrevivência. Além disso, pode se mover com seu deslocamento normal enquanto rastreia sem sofrer penalidades no teste de Sobrevivência.',
      prerequisites: [],
    },
    {
      id: 'explorador',
      name: 'Explorador',
      type: 'Habilidade base',
      level: 3,
      description: 'No 3º nível, escolha um tipo de terreno entre aquático, ártico, colina, deserto, floresta, montanha, pântano, planície, subterrâneo ou urbano. A partir do 11º nível, você também pode escolher área de Tormenta. Quando estiver no tipo de terreno escolhido, você soma sua Sabedoria (mínimo +1) na Defesa e nos testes de Acrobacia, Atletismo, Furtividade, Percepção e Sobrevivência. A cada quatro níveis, escolha outro tipo de terreno para receber o bônus ou aumente o bônus em um tipo de terreno já escolhido em +2.',
      prerequisites: [{ type: 'level', value: 3 }],
      grantsSelection: 'Terreno',
    },
    {
      id: 'explorador_7',
      name: 'Explorador (Aprimoramento)',
      type: 'Habilidade base',
      level: 7,
      description: 'Escolha outro tipo de terreno para receber o bônus ou aumente o bônus em um tipo de terreno já escolhido em +2.',
      prerequisites: [{ type: 'level', value: 7 }],
      grantsSelection: 'Terreno',
    },
    {
      id: 'explorador_11',
      name: 'Explorador (Aprimoramento)',
      type: 'Habilidade base',
      level: 11,
      description: 'Escolha outro tipo de terreno para receber o bônus ou aumente o bônus em um tipo de terreno já escolhido em +2.',
      prerequisites: [{ type: 'level', value: 11 }],
      grantsSelection: 'Terreno',
    },
    {
      id: 'explorador_15',
      name: 'Explorador (Aprimoramento)',
      type: 'Habilidade base',
      level: 15,
      description: 'Escolha outro tipo de terreno para receber o bônus ou aumente o bônus em um tipo de terreno já escolhido em +2.',
      prerequisites: [{ type: 'level', value: 15 }],
      grantsSelection: 'Terreno',
    },
    {
      id: 'explorador_19',
      name: 'Explorador (Aprimoramento)',
      type: 'Habilidade base',
      level: 19,
      description: 'Escolha outro tipo de terreno para receber o bônus ou aumente o bônus em um tipo de terreno já escolhido em +2.',
      prerequisites: [{ type: 'level', value: 19 }],
      grantsSelection: 'Terreno',
    },
    // Poderes de Caçador
    {
      id: 'ambidestria',
      name: 'Ambidestria',
      type: 'Poder',
      description: 'Se estiver empunhando duas armas (e pelo menos uma delas for leve) e fizer a ação agredir, você pode fazer dois ataques, um com cada arma. Se fizer isso, sofre –2 em todos os testes de ataque até o seu próximo turno.',
      prerequisites: [{ type: 'attribute', key: 'destreza', value: 2 }],
    },
    {
      id: 'armadilha_arataca',
      name: 'Armadilha: Arataca',
      type: 'Poder',
      tags: ['armadilha'],
      description: 'A vítima sofre 2d6 pontos de dano de perfuração e fica agarrada. Uma criatura agarrada pode escapar com uma ação padrão e um teste de Força ou Acrobacia (CD Sab).',
      prerequisites: [],
    },
    {
      id: 'armadilha_espinhos',
      name: 'Armadilha: Espinhos',
      type: 'Poder',
      tags: ['armadilha'],
      description: 'A vítima sofre 6d6 pontos de dano de perfuração. Um teste de Reflexos (CD Sab) reduz o dano à metade.',
      prerequisites: [],
    },
    {
      id: 'armadilha_laco',
      name: 'Armadilha: Laço',
      type: 'Poder',
      tags: ['armadilha'],
      description: 'A vítima deve fazer um teste de Reflexos (CD Sab). Se passar, fica caída. Se falhar, fica agarrada. Uma criatura agarrada pode se soltar com uma ação padrão e um teste de Força ou Acrobacia (CD Sab).',
      prerequisites: [],
    },
    {
      id: 'armadilha_rede',
      name: 'Armadilha: Rede',
      type: 'Poder',
      tags: ['armadilha'],
      description: 'Todas as criaturas na área ficam enredadas e não podem sair da área. Uma vítima pode se libertar com uma ação padrão e um teste de Força ou Acrobacia (CD 25). Além disso, a área ocupada pela rede é considerada terreno difícil. Nesta armadilha você escolhe quantas criaturas precisam estar na área para ativá-la.',
      prerequisites: [],
    },
    {
      id: 'armadilheiro',
      name: 'Armadilheiro',
      type: 'Poder',
      description: 'Você soma sua Sabedoria no dano e na CD de suas armadilhas (cumulativo).',
      prerequisites: [{ type: 'tag', value: 'armadilha' }, { type: 'level', value: 5 }],
    },
    {
      id: 'arqueiro',
      name: 'Arqueiro',
      type: 'Poder',
      description: 'Se estiver usando uma arma de ataque à distância, você soma sua Sabedoria nas rolagens de dano (limitado pelo seu nível).',
      prerequisites: [{ type: 'attribute', key: 'sabedoria', value: 1 }],
    },
    {
      id: 'aumento_atributo',
      name: 'Aumento de Atributo',
      type: 'Poder',
      description: 'Você recebe +1 em um atributo. Você pode escolher este poder várias vezes, mas apenas uma vez por patamar para um mesmo atributo.',
      prerequisites: [],
    },
    {
      id: 'bote',
      name: 'Bote',
      type: 'Poder',
      description: 'Se estiver empunhando duas armas e fizer uma investida, você pode pagar 1 PM para fazer um ataque adicional com sua arma secundária.',
      prerequisites: [{ type: 'Poder', value: 'ambidestria' }, { type: 'level', value: 6 }],
    },
    {
      id: 'caminhos_natureza',
      name: 'Caminhos da Natureza',
      type: 'Poder',
      description: 'Você aprende e pode lançar Caminhos da Natureza (atributo-chave Sabedoria).',
      prerequisites: [{ type: 'attribute', key: 'sabedoria', value: 1 }, { type: 'level', value: 3 }],
    },
    {
      id: 'camuflagem',
      name: 'Camuflagem',
      type: 'Poder',
      description: 'Você pode gastar 2 PM para se esconder mesmo sem camuflagem ou cobertura disponível.',
      prerequisites: [{ type: 'level', value: 6 }],
    },
    {
      id: 'chuva_laminas',
      name: 'Chuva de Lâminas',
      type: 'Poder',
      description: 'Uma vez por rodada, quando usa Ambidestria, você pode pagar 2 PM para fazer um ataque adicional com sua arma primária.',
      prerequisites: [{ type: 'attribute', key: 'destreza', value: 4 }, { type: 'Poder', value: 'ambidestria' }, { type: 'level', value: 12 }],
    },
    {
      id: 'companheiro_animal',
      name: 'Companheiro Animal',
      type: 'Poder',
      description: 'Você recebe um companheiro animal.',
      prerequisites: [{ type: 'attribute', key: 'carisma', value: 1 }, { type: 'skill', value: 'adestramento' }],
    },
    {
      id: 'elo_natureza',
      name: 'Elo com a Natureza',
      type: 'Poder',
      description: 'Você soma sua Sabedoria em seu total de pontos de mana e aprende e pode lançar Caminhos da Natureza (atributo-chave Sabedoria).',
      prerequisites: [{ type: 'attribute', key: 'sabedoria', value: 1 }, { type: 'level', value: 3 }],
    },
    {
      id: 'emboscar',
      name: 'Emboscar',
      type: 'Poder',
      description: 'Você pode gastar 2 PM para realizar uma ação padrão adicional em seu turno. Você só pode usar este poder na primeira rodada de um combate.',
      prerequisites: [{ type: 'skill', value: 'furtividade' }],
    },
    {
      id: 'empatia_selvagem',
      name: 'Empatia Selvagem',
      type: 'Poder',
      description: 'Você pode se comunicar com animais por meio de linguagem corporal e vocalizações. Você pode usar Adestramento com animais para mudar atitude e persuasão (veja Diplomacia).',
      prerequisites: [],
    },
    {
      id: 'escalamuca',
      name: 'Escaramuça',
      type: 'Poder',
      description: 'Quando se move 6m ou mais, você recebe +2 na Defesa e Reflexos e +1d8 nas rolagens de dano de ataques corpo a corpo e à distância em alcance curto até o início de seu próximo turno. Você não pode usar esta habilidade se estiver vestindo armadura pesada.',
      prerequisites: [{ type: 'attribute', key: 'destreza', value: 2 }, { type: 'level', value: 6 }],
    },
    {
      id: 'escalamuca_superior',
      name: 'Escaramuça Superior',
      type: 'Poder',
      description: 'Quando usa Escaramuça, seus bônus aumentam para +5 na Defesa e Reflexos e +1d12 em rolagens de dano.',
      prerequisites: [{ type: 'Poder', value: 'escalamuca' }, { type: 'level', value: 12 }],
    },
    {
      id: 'espreitar',
      name: 'Espreitar',
      type: 'Poder',
      description: 'Quando usa a habilidade Marca da Presa, você recebe um bônus de +1 em testes de perícia contra a criatura marcada. Esse bônus aumenta em +1 para cada PM adicional gasto na habilidade e também dobra com a habilidade Inimigo.',
      prerequisites: [],
    },
    {
      id: 'ervas_curativas',
      name: 'Ervas Curativas',
      type: 'Poder',
      description: 'Você pode gastar uma ação completa e uma quantidade de PM a sua escolha (limitado por sua Sabedoria) para aplicar ervas que curam ou desintoxicam em você ou num aliado adjacente. Para cada PM que gastar, cura 2d6 PV ou remove uma condição envenenado afetando o alvo.',
      prerequisites: [],
    },
    {
      id: 'impeto',
      name: 'Ímpeto',
      type: 'Poder',
      description: 'Você pode gastar 1 PM para aumentar seu deslocamento em +6m por uma rodada.',
      prerequisites: [],
    },
    {
      id: 'inimigo_animal',
      name: 'Inimigo de Animal',
      type: 'Poder',
      description: 'Quando você usa a habilidade Marca da Presa contra uma criatura do tipo animal, dobra os dados de bônus no dano.',
      prerequisites: [],
    },
    {
      id: 'inimigo_construto',
      name: 'Inimigo de Construto',
      type: 'Poder',
      description: 'Quando você usa a habilidade Marca da Presa contra uma criatura do tipo construto, dobra os dados de bônus no dano.',
      prerequisites: [],
    },
    {
      id: 'inimigo_espirito',
      name: 'Inimigo de Espírito',
      type: 'Poder',
      description: 'Quando você usa a habilidade Marca da Presa contra uma criatura do tipo espírito, dobra os dados de bônus no dano.',
      prerequisites: [],
    },
    {
      id: 'inimigo_monstro',
      name: 'Inimigo de Monstro',
      type: 'Poder',
      description: 'Quando você usa a habilidade Marca da Presa contra uma criatura do tipo monstro, dobra os dados de bônus no dano.',
      prerequisites: [],
    },
    {
      id: 'inimigo_morto_vivo',
      name: 'Inimigo de Morto-Vivo',
      type: 'Poder',
      description: 'Quando você usa a habilidade Marca da Presa contra uma criatura do tipo morto-vivo, dobra os dados de bônus no dano.',
      prerequisites: [],
    },
    {
      id: 'olho_falcao',
      name: 'Olho do Falcão',
      type: 'Poder',
      description: 'Você pode usar a habilidade Marca da Presa em criaturas em alcance longo.',
      prerequisites: [],
    },
    {
      id: 'ponto_fraco',
      name: 'Ponto Fraco',
      type: 'Poder',
      description: 'Quando usa a habilidade Marca da Presa, seus ataques contra a criatura marcada recebem +2 na margem de ameaça. Esse bônus dobra com a habilidade Inimigo.',
      prerequisites: [],
    },
    {
      id: 'explorador_aquatico',
      name: 'Explorador (Aquático)',
      type: 'Terreno',
      description: 'Quando estiver no tipo de terreno aquático, você soma sua Sabedoria (mínimo +1) na Defesa e nos testes de Acrobacia, Atletismo, Furtividade, Percepção e Sobrevivência.',
      prerequisites: [],
    },
    {
      id: 'explorador_artico',
      name: 'Explorador (Ártico)',
      type: 'Terreno',
      description: 'Quando estiver no tipo de terreno ártico, você soma sua Sabedoria (mínimo +1) na Defesa e nos testes de Acrobacia, Atletismo, Furtividade, Percepção e Sobrevivência.',
      prerequisites: [],
    },
    {
      id: 'explorador_colina',
      name: 'Explorador (Colina)',
      type: 'Terreno',
      description: 'Quando estiver no tipo de terreno colina, você soma sua Sabedoria (mínimo +1) na Defesa e nos testes de Acrobacia, Atletismo, Furtividade, Percepção e Sobrevivência.',
      prerequisites: [],
    },
    {
      id: 'explorador_deserto',
      name: 'Explorador (Deserto)',
      type: 'Terreno',
      description: 'Quando estiver no tipo de terreno deserto, você soma sua Sabedoria (mínimo +1) na Defesa e nos testes de Acrobacia, Atletismo, Furtividade, Percepção e Sobrevivência.',
      prerequisites: [],
    },
    {
      id: 'explorador_floresta',
      name: 'Explorador (Floresta)',
      type: 'Terreno',
      description: 'Quando estiver no tipo de terreno floresta, você soma sua Sabedoria (mínimo +1) na Defesa e nos testes de Acrobacia, Atletismo, Furtividade, Percepção e Sobrevivência.',
      prerequisites: [],
    },
    {
      id: 'explorador_montanha',
      name: 'Explorador (Montanha)',
      type: 'Terreno',
      description: 'Quando estiver no tipo de terreno montanha, você soma sua Sabedoria (mínimo +1) na Defesa e nos testes de Acrobacia, Atletismo, Furtividade, Percepção e Sobrevivência.',
      prerequisites: [],
    },
    {
      id: 'explorador_pantano',
      name: 'Explorador (Pântano)',
      type: 'Terreno',
      description: 'Quando estiver no tipo de terreno pântano, você soma sua Sabedoria (mínimo +1) na Defesa e nos testes de Acrobacia, Atletismo, Furtividade, Percepção e Sobrevivência.',
      prerequisites: [],
    },
    {
      id: 'explorador_planicie',
      name: 'Explorador (Planície)',
      type: 'Terreno',
      description: 'Quando estiver no tipo de terreno planície, você soma sua Sabedoria (mínimo +1) na Defesa e nos testes de Acrobacia, Atletismo, Furtividade, Percepção e Sobrevivência.',
      prerequisites: [],
    },

    {
      id: 'explorador_subterraneo',
      name: 'Explorador (Subterrâneo)',
      type: 'Terreno',
      description: 'Quando estiver no tipo de terreno subterrâneo, você soma sua Sabedoria (mínimo +1) na Defesa e nos testes de Acrobacia, Atletismo, Furtividade, Percepção e Sobrevivência.',
      prerequisites: [],
    },

    {
      id: 'explorador_urbano',
      name: 'Explorador (Urbano)',
      type: 'Terreno',
      description: 'Quando estiver no tipo de terreno urbano, você soma sua Sabedoria (mínimo +1) na Defesa e nos testes de Acrobacia, Atletismo, Furtividade, Percepção e Sobrevivência.',
      prerequisites: [],
    },

    {
      id: 'explorador_tormenta',
      name: 'Explorador (Tormenta)',
      type: 'Terreno',
      description: 'Quando estiver em área de Tormenta, você soma sua Sabedoria (mínimo +1) na Defesa e nos testes de Acrobacia, Atletismo, Furtividade, Percepção e Sobrevivência.',
      prerequisites: [{ type: 'level', value: 11 }],
    },

    {
      id: 'caminho_explorador',
      name: 'Caminho do Explorador',
      type: 'Habilidade base',
      description: 'Você pode atravessar terrenos difíceis sem sofrer redução em seu deslocamento e a CD para rastrear você aumenta em +10. Esta habilidade só funciona em terrenos nos quais você tenha a habilidade Explorador.',
      prerequisites: [{ type: 'level', value: 5 }],
    },
    {
      id: 'mestre_cacador',
      name: 'Mestre Caçador',
      type: 'Habilidade base',
      description: 'Você pode usar a habilidade Marca da Presa como uma ação livre. Além disso, quando usa a habilidade, pode pagar 5 PM para aumentar sua margem de ameaça contra a criatura em +2. Se você reduzir uma criatura contra a qual usou Marca da Presa a 0 pontos de vida, recupera 5 PM.',
      prerequisites: [{ type: 'level', value: 20 }],
    },
  ],
  // Placeholder para outras classes
  arcanista: [
    // ==================== HABILIDADES BASE ====================
    {
      id: 'caminho_arcanista',
      name: 'Caminho do Arcanista',
      type: 'Habilidade base',
      level: 1,
      description: 'A magia é um poder incrível, capaz de alterar a realidade. Esse poder tem fontes distintas e cada uma opera conforme suas próprias regras. Escolha uma das opções: Bruxo, Feiticeiro ou Mago. Uma vez feita, essa escolha não pode ser mudada.',
      prerequisites: [],
      grantsSelection: 'Caminho',
    },
    {
      id: 'magias_1_circulo',
      name: 'Magias (1º Círculo)',
      type: 'Habilidade base',
      level: 1,
      description: 'Você pode lançar magias arcanas de 1º círculo. Você começa com três magias de 1º círculo. A cada nível, aprende uma magia de qualquer círculo que possa lançar.',
      prerequisites: [],
    },
    {
      id: 'magias_2_circulo',
      name: 'Magias (2º Círculo)',
      type: 'Habilidade base',
      level: 5,
      description: 'Você pode lançar magias arcanas de 2º círculo.',
      prerequisites: [{ type: 'level', value: 5 }],
    },
    {
      id: 'magias_3_circulo',
      name: 'Magias (3º Círculo)',
      type: 'Habilidade base',
      level: 9,
      description: 'Você pode lançar magias arcanas de 3º círculo.',
      prerequisites: [{ type: 'level', value: 9 }],
    },
    {
      id: 'magias_4_circulo',
      name: 'Magias (4º Círculo)',
      type: 'Habilidade base',
      level: 13,
      description: 'Você pode lançar magias arcanas de 4º círculo.',
      prerequisites: [{ type: 'level', value: 13 }],
    },
    {
      id: 'magias_5_circulo',
      name: 'Magias (5º Círculo)',
      type: 'Habilidade base',
      level: 17,
      description: 'Você pode lançar magias arcanas de 5º círculo.',
      prerequisites: [{ type: 'level', value: 17 }],
    },
    {
      id: 'alta_arcana',
      name: 'Alta Arcana',
      type: 'Habilidade base',
      level: 20,
      description: 'No 20º nível, seu domínio das artes arcanas é total. O custo em PM de suas magias arcanas é reduzido à metade (após aplicar aprimoramentos e quaisquer outros efeitos que reduzam custo).',
      prerequisites: [{ type: 'level', value: 20 }],
    },
    // ==================== CAMINHOS ====================
    {
      id: 'caminho_bruxo',
      name: 'Bruxo',
      type: 'Caminho',
      description: 'Você lança magias através de um foco — uma varinha, cajado, chapéu... Para lançar uma magia, você precisa empunhar o foco com uma mão (e gesticular com a outra) ou fazer um teste de Misticismo (CD 20 + o custo em PM da magia; se falhar, a magia não funciona, mas você gasta os PM mesmo assim). O foco tem RD 10 e PV iguais à metade dos seus, independentemente de seu material ou forma. Se for danificado, é totalmente restaurado na próxima vez que você recuperar seus PM. Se for destruído (reduzido a 0 PV), você fica atordoado por uma rodada. Você pode recuperar um foco destruído ou perdido com uma semana de trabalho e T$ 100. Seu atributo-chave para magias é Inteligência.',
      prerequisites: [],
    },
    {
      id: 'caminho_feiticeiro',
      name: 'Feiticeiro',
      type: 'Caminho',
      description: 'Você lança magias através de um poder inato que corre em seu sangue. Escolha uma linhagem como origem de seus poderes. Você recebe a herança básica da linhagem escolhida. Você não depende de nenhum item ou estudo, mas sua capacidade de aprender magias é limitada — você aprende uma magia nova a cada nível ímpar (3º, 5º, 7º etc.), em vez de a cada nível. Seu atributo-chave para magias é Carisma.',
      prerequisites: [],
    },
    {
      id: 'caminho_mago',
      name: 'Mago',
      type: 'Caminho',
      description: 'Você lança magias através de estudo e memorização de fórmulas arcanas. Você só pode lançar magias memorizadas; suas outras magias não podem ser lançadas, mesmo que você tenha pontos de mana para tal. Para memorizar magias, você precisa estudar seu grimório por uma hora. Quando faz isso, escolhe metade das magias que conhece. Essas serão suas magias memorizadas. Você pode memorizar magias uma vez por dia. Caso não possa estudar, não poderá trocar suas magias memorizadas. Um grimório tem as mesmas estatísticas de um foco e pode ser recuperado da mesma forma. Você começa com uma magia adicional (para um total de 4) e, sempre que ganha acesso a um novo círculo de magias, aprende uma magia adicional daquele círculo. Seu atributo-chave para magias é Inteligência.',
      prerequisites: [],
    },
    // ==================== ESCOLAS DE MAGIA ====================
    {
      id: 'escola_abjuracao',
      name: 'Abjuração',
      type: 'Escola',
      description: 'Magias de proteção, que anulam outras magias ou expulsam criaturas invocadas de volta a seus planos de existência nativos.',
      prerequisites: [],
    },
    {
      id: 'escola_adivinhacao',
      name: 'Adivinhação',
      type: 'Escola',
      description: 'Magias de detecção ou que vasculham passado e futuro.',
      prerequisites: [],
    },
    {
      id: 'escola_convocacao',
      name: 'Convocação',
      type: 'Escola',
      description: 'Magias que transportam matéria. Esse transporte é realizado através do Éter Entre Mundos; por isso, qualquer efeito que bloqueia viagens etéreas também impede convocações. Criaturas convocadas surgem em uma superfície desocupada e, quando destruídas, desaparecem e são devolvidas a seus mundos nativos.',
      prerequisites: [],
    },
    {
      id: 'escola_encantamento',
      name: 'Encantamento',
      type: 'Escola',
      description: 'Magias que afetam a mente. Todas as magias de encantamento são efeitos mentais.',
      prerequisites: [],
    },
    {
      id: 'escola_evocacao',
      name: 'Evocação',
      type: 'Escola',
      description: 'Magias que manipulam ou geram energia pura. Ácido, eletricidade, fogo e frio são as energias geradas pelos quatro elementos, respectivamente terra, ar, fogo e água. Luz é energia positiva. Essência é energia mágica pura.',
      prerequisites: [],
    },
    {
      id: 'escola_ilusao',
      name: 'Ilusão',
      type: 'Escola',
      description: 'Essas magias fazem outros perceberem algo que não existe ou ignorarem algo real. Todas as magias de ilusão são efeitos mentais.',
      prerequisites: [],
    },
    {
      id: 'escola_necromancia',
      name: 'Necromancia',
      type: 'Escola',
      description: 'Magias que canalizam energia negativa, criando escuridão, drenando a força vital de criaturas vivas e criando mortos-vivos. Magias de necromancia são efeitos de trevas.',
      prerequisites: [],
    },
    {
      id: 'escola_transmutacao',
      name: 'Transmutação',
      type: 'Escola',
      description: 'Magias que alteram as propriedades físicas de uma criatura ou objeto.',
      prerequisites: [],
    },
    // ==================== PODERES DE ARCANISTA ====================
    {
      id: 'arcano_batalha',
      name: 'Arcano de Batalha',
      type: 'Poder',
      description: 'Quando lança uma magia, você soma seu atributo-chave na rolagem de dano.',
      prerequisites: [],
    },
    {
      id: 'aumento_atributo_arcanista',
      name: 'Aumento de Atributo',
      type: 'Poder',
      description: 'Você recebe +1 em um atributo. Você pode escolher este poder várias vezes, mas apenas uma vez por patamar para um mesmo atributo.',
      prerequisites: [],
    },
    {
      id: 'caldeirao_bruxo',
      name: 'Caldeirão do Bruxo',
      type: 'Poder',
      description: 'Você pode criar poções, como se tivesse o poder geral Preparar Poção. Se tiver ambos, pode criar poções de até 5º círculo.',
      prerequisites: [{ type: 'Caminho', value: 'caminho_bruxo' }, { type: 'skill', value: 'oficio' }],
    },
    {
      id: 'conhecimento_magico',
      name: 'Conhecimento Mágico',
      type: 'Poder',
      description: 'Você aprende duas magias de qualquer círculo que possa lançar. Você pode escolher este poder quantas vezes quiser.',
      prerequisites: [],
    },
    {
      id: 'contramagica_aprimorada',
      name: 'Contramágica Aprimorada',
      type: 'Poder',
      description: 'Uma vez por rodada, você pode fazer uma contramágica como uma reação.',
      prerequisites: [{ type: 'magia', value: 'dissipar_magia' }],
    },
    {
      id: 'envolto_misterio',
      name: 'Envolto em Mistério',
      type: 'Poder',
      description: 'Sua aparência e postura assombrosas o permitem manipular e assustar pessoas ignorantes ou supersticiosas. O mestre define o que exatamente você pode fazer e quem se encaixa nessa descrição. Como regra geral, você recebe +5 em Enganação e Intimidação contra pessoas não treinadas em Conhecimento ou Misticismo.',
      prerequisites: [],
    },
    {
      id: 'escriba_arcano',
      name: 'Escriba Arcano',
      type: 'Poder',
      description: 'Você pode aprender magias copiando os textos de pergaminhos e grimórios de outros magos. Aprender uma magia dessa forma exige um dia de trabalho e T$ 250 em matérias-primas por PM necessário para lançar a magia.',
      prerequisites: [{ type: 'Caminho', value: 'caminho_mago' }, { type: 'skill', value: 'oficio' }],
    },
    {
      id: 'especialista_escola',
      name: 'Especialista em Escola',
      type: 'Poder',
      description: 'Escolha uma escola de magia. A CD para resistir a suas magias dessa escola aumenta em +2.',
      prerequisites: [{ type: 'Caminho', value: 'caminho_bruxo|caminho_mago' }],
      grantsSelection: 'Escola',
    },
    {
      id: 'familiar',
      name: 'Familiar',
      type: 'Poder',
      description: 'Você possui um animal de estimação mágico. Escolha um animal Minúsculo ou Pequeno. Ele se torna um parceiro especial seu.',
      prerequisites: [],
    },
    {
      id: 'fluxo_mana',
      name: 'Fluxo de Mana',
      type: 'Poder',
      description: 'Você pode manter dois efeitos sustentados ativos simultaneamente com apenas uma ação livre, pagando o custo de cada efeito separadamente.',
      prerequisites: [{ type: 'level', value: 10 }],
    },
    {
      id: 'foco_vital',
      name: 'Foco Vital',
      type: 'Poder',
      description: 'Se você estiver segurando seu foco e sofrer dano que o levaria a 0 PV ou menos, você fica com 1 PV e o foco perde PV igual ao valor excedente ou até ser destruído (se o foco for destruído, você sofre o dano excedente).',
      prerequisites: [{ type: 'Caminho', value: 'caminho_bruxo' }],
    },
    {
      id: 'fortalecimento_arcano',
      name: 'Fortalecimento Arcano',
      type: 'Poder',
      description: 'A CD para resistir a suas magias aumenta em +1. Se você puder lançar magias de 4º círculo, em vez disso ela aumenta em +2.',
      prerequisites: [{ type: 'level', value: 5 }],
    },
    {
      id: 'heranca_aprimorada',
      name: 'Herança Aprimorada',
      type: 'Poder',
      description: 'Você recebe a herança aprimorada de sua linhagem sobrenatural.',
      prerequisites: [{ type: 'Caminho', value: 'caminho_feiticeiro' }, { type: 'level', value: 6 }],
    },
    {
      id: 'heranca_superior',
      name: 'Herança Superior',
      type: 'Poder',
      description: 'Você recebe a herança superior de sua linhagem sobrenatural.',
      prerequisites: [{ type: 'Poder', value: 'heranca_aprimorada' }, { type: 'level', value: 11 }],
    },
    {
      id: 'magia_pungente',
      name: 'Magia Pungente',
      type: 'Poder',
      description: 'Quando lança uma magia, você pode pagar 1 PM para aumentar em +2 a CD para resistir a ela.',
      prerequisites: [],
    },
    {
      id: 'mestre_escola',
      name: 'Mestre em Escola',
      type: 'Poder',
      description: 'Escolha uma escola de magia. O custo para lançar magias dessa escola diminui em –1 PM.',
      prerequisites: [{ type: 'Poder', value: 'especialista_escola' }, { type: 'level', value: 8 }],
    },
    {
      id: 'poder_magico',
      name: 'Poder Mágico',
      type: 'Poder',
      description: 'Você recebe +1 ponto de mana por nível de arcanista. Quando sobe de nível, os PM que recebe por este poder aumentam de acordo.',
      prerequisites: [],
    },
    {
      id: 'raio_arcano',
      name: 'Raio Arcano',
      type: 'Poder',
      description: 'Você pode gastar uma ação padrão para causar 1d8 pontos de dano de essência num alvo em alcance curto. Esse dano aumenta em +1d8 para cada círculo de magia acima do 1º que você puder lançar. O alvo pode fazer um teste de Reflexos (CD atributo-chave) para reduzir o dano à metade. O raio arcano conta como uma magia para efeitos de habilidades e itens que beneficiem suas magias.',
      prerequisites: [],
    },
    {
      id: 'raio_elemental',
      name: 'Raio Elemental',
      type: 'Poder',
      description: 'Quando usa Raio Arcano, você pode pagar 1 PM para que ele cause dano de ácido, eletricidade, fogo, frio ou trevas, a sua escolha. Se o alvo falhar no teste de Reflexos, sofre uma condição, de acordo com o tipo de dano. Ácido: vulnerável por 1 rodada. Eletricidade: ofuscado por 1 rodada. Fogo: fica em chamas. Frio: lento por 1 rodada. Trevas: não pode curar PV por 1 rodada.',
      prerequisites: [{ type: 'Poder', value: 'raio_arcano' }],
    },
    {
      id: 'raio_poderoso',
      name: 'Raio Poderoso',
      type: 'Poder',
      description: 'Os dados de dano do seu Raio Arcano aumentam para d12 e o alcance dele aumenta para médio.',
      prerequisites: [{ type: 'Poder', value: 'raio_arcano' }],
    },
    {
      id: 'tinta_mago',
      name: 'Tinta do Mago',
      type: 'Poder',
      description: 'Você pode criar pergaminhos, como se tivesse o poder Escrever Pergaminho. Se tiver ambos, seu custo para criar pergaminhos é reduzido à metade.',
      prerequisites: [{ type: 'Caminho', value: 'caminho_mago' }, { type: 'skill', value: 'oficio' }],
    },
  ],
  barbaro: [
    // ==================== HABILIDADES BASE ====================
    {
      id: 'furia',
      name: 'Fúria',
      type: 'Habilidade base',
      level: 1,
      description: 'Você pode gastar 2 PM para invocar uma fúria selvagem. Você recebe +2 em testes de ataque e rolagens de dano corpo a corpo, mas não pode fazer nenhuma ação que exija calma e concentração (como usar a perícia Furtividade ou lançar magias). A cada cinco níveis, pode gastar +1 PM para aumentar os bônus em +1. A Fúria termina se, ao fim da rodada, você não tiver atacado nem sido alvo de um efeito (ataque, habilidade, magia...) hostil.',
      prerequisites: [],
    },
    {
      id: 'instinto_selvagem',
      name: 'Instinto Selvagem',
      type: 'Habilidade base',
      level: 3,
      description: 'No 3º nível, você recebe +1 em rolagens de dano, Percepção e Reflexos. A cada seis níveis, esse bônus aumenta em +1.',
      prerequisites: [{ type: 'level', value: 3 }],
    },
    {
      id: 'instinto_selvagem_9',
      name: 'Instinto Selvagem (+2)',
      type: 'Habilidade base',
      level: 9,
      description: 'Seu bônus de Instinto Selvagem aumenta para +2 em rolagens de dano, Percepção e Reflexos.',
      prerequisites: [{ type: 'level', value: 9 }],
    },
    {
      id: 'instinto_selvagem_15',
      name: 'Instinto Selvagem (+3)',
      type: 'Habilidade base',
      level: 15,
      description: 'Seu bônus de Instinto Selvagem aumenta para +3 em rolagens de dano, Percepção e Reflexos.',
      prerequisites: [{ type: 'level', value: 15 }],
    },
    {
      id: 'reducao_dano_2',
      name: 'Redução de Dano 2',
      type: 'Habilidade base',
      level: 5,
      description: 'A partir do 5º nível, graças a seu vigor e força de vontade, você ignora parte de seus ferimentos. Você recebe redução de dano 2 (todo dano que sofre é reduzido em 2).',
      prerequisites: [{ type: 'level', value: 5 }],
    },
    {
      id: 'reducao_dano_4',
      name: 'Redução de Dano 4',
      type: 'Habilidade base',
      level: 8,
      description: 'Sua redução de dano aumenta para 4.',
      prerequisites: [{ type: 'level', value: 8 }],
    },
    {
      id: 'reducao_dano_6',
      name: 'Redução de Dano 6',
      type: 'Habilidade base',
      level: 11,
      description: 'Sua redução de dano aumenta para 6.',
      prerequisites: [{ type: 'level', value: 11 }],
    },
    {
      id: 'reducao_dano_8',
      name: 'Redução de Dano 8',
      type: 'Habilidade base',
      level: 14,
      description: 'Sua redução de dano aumenta para 8.',
      prerequisites: [{ type: 'level', value: 14 }],
    },
    {
      id: 'reducao_dano_10',
      name: 'Redução de Dano 10',
      type: 'Habilidade base',
      level: 17,
      description: 'Sua redução de dano aumenta para 10 (máximo).',
      prerequisites: [{ type: 'level', value: 17 }],
    },
    {
      id: 'furia_titanica',
      name: 'Fúria Titânica',
      type: 'Habilidade base',
      level: 20,
      description: 'No 20º nível, o bônus que você recebe nos testes de ataque e rolagens de dano quando usa Fúria é dobrado. Por exemplo, se gastar 5 PM, em vez de um bônus de +5, recebe um bônus de +10.',
      prerequisites: [{ type: 'level', value: 20 }],
    },
    // ==================== PODERES DE BÁRBARO ====================
    {
      id: 'alma_bronze',
      name: 'Alma de Bronze',
      type: 'Poder',
      description: 'Quando entra em fúria, você recebe uma quantidade de pontos de vida temporários igual a seu nível + sua Força.',
      prerequisites: [],
    },
    {
      id: 'aumento_atributo_barbaro',
      name: 'Aumento de Atributo',
      type: 'Poder',
      description: 'Você recebe +1 em um atributo. Você pode escolher este poder várias vezes, mas apenas uma vez por patamar para um mesmo atributo.',
      prerequisites: [],
    },
    {
      id: 'brado_assustador',
      name: 'Brado Assustador',
      type: 'Poder',
      tags: ['medo'],
      description: 'Você pode gastar uma ação de movimento e 1 PM para soltar um berro feroz. Todos os inimigos em alcance curto ficam vulneráveis até o fim da cena.',
      prerequisites: [{ type: 'skill', value: 'intimidacao' }],
    },
    {
      id: 'critico_brutal',
      name: 'Crítico Brutal',
      type: 'Poder',
      description: 'Seu multiplicador de crítico com armas corpo a corpo e de arremesso aumenta em +1. Por exemplo, seu multiplicador com um machado de batalha (normalmente x3) será x4.',
      prerequisites: [{ type: 'level', value: 6 }],
    },
    {
      id: 'destruidor',
      name: 'Destruidor',
      type: 'Poder',
      description: 'Quando causa dano com uma arma corpo a corpo de duas mãos, você pode rolar novamente qualquer resultado 1 ou 2 das rolagens de dano da arma.',
      prerequisites: [{ type: 'attribute', key: 'forca', value: 1 }],
    },
    {
      id: 'espirito_inquebravel',
      name: 'Espírito Inquebrável',
      type: 'Poder',
      description: 'Enquanto está em fúria, você não fica inconsciente por estar com 0 PV ou menos (você ainda morre se chegar em um valor negativo igual à metade de seus pontos de vida máximos).',
      prerequisites: [{ type: 'Poder', value: 'alma_bronze' }],
    },
    {
      id: 'esquiva_sobrenatural',
      name: 'Esquiva Sobrenatural',
      type: 'Poder',
      description: 'Seus instintos são tão apurados que você consegue reagir ao perigo antes que seus sentidos o percebam. Você nunca fica surpreendido.',
      prerequisites: [],
    },
    {
      id: 'forca_indomavel',
      name: 'Força Indomável',
      type: 'Poder',
      description: 'Você pode gastar 1 PM para somar seu nível em um teste de Força ou Atletismo. Você pode usar esta habilidade depois de rolar o dado, mas deve usá-la antes de o mestre dizer se você passou ou não.',
      prerequisites: [],
    },
    {
      id: 'frenesi',
      name: 'Frenesi',
      type: 'Poder',
      description: 'Uma vez por rodada, se estiver em fúria e usar a ação agredir para fazer um ataque corpo a corpo ou com uma arma de arremesso, você pode gastar 2 PM para fazer um ataque adicional.',
      prerequisites: [],
    },
    {
      id: 'furia_savana',
      name: 'Fúria da Savana',
      type: 'Poder',
      description: 'Seu deslocamento aumenta em +3m. Quando usa Fúria, você aplica o bônus em ataque e dano também a armas de arremesso.',
      prerequisites: [],
    },
    {
      id: 'furia_raivosa',
      name: 'Fúria Raivosa',
      type: 'Poder',
      description: 'Se sua Fúria for terminar por você não ter atacado nem sido alvo de um efeito hostil, você pode pagar 1 PM para continuar em fúria nesta rodada. Se você atacar ou for atacado na rodada seguinte, sua fúria continua normalmente.',
      prerequisites: [],
    },
    {
      id: 'golpe_poderoso',
      name: 'Golpe Poderoso',
      type: 'Poder',
      description: 'Ao acertar um ataque corpo a corpo ou com uma arma de arremesso, você pode gastar 1 PM para causar um dado extra de dano do mesmo tipo (por exemplo, com um montante, causa +1d6, para um dano total de 3d6; com um machado de guerra, causa +1d12, para um dano total de 2d12).',
      prerequisites: [],
    },
    {
      id: 'impeto_barbaro',
      name: 'Ímpeto',
      type: 'Poder',
      description: 'Você pode gastar 1 PM para aumentar seu deslocamento em +6m por uma rodada.',
      prerequisites: [],
    },
    {
      id: 'investida_imprudente',
      name: 'Investida Imprudente',
      type: 'Poder',
      description: 'Quando faz uma investida, você pode aumentar sua penalidade na Defesa pela investida para –5 para receber um bônus de +1d12 na rolagem de dano deste ataque.',
      prerequisites: [],
    },
    {
      id: 'pele_aco',
      name: 'Pele de Aço',
      type: 'Poder',
      description: 'O bônus de Pele de Ferro aumenta para +8.',
      prerequisites: [{ type: 'Poder', value: 'pele_ferro' }, { type: 'level', value: 8 }],
    },
    {
      id: 'pele_ferro',
      name: 'Pele de Ferro',
      type: 'Poder',
      description: 'Você recebe +4 na Defesa, mas apenas se não estiver usando armadura pesada.',
      prerequisites: [],
    },
    {
      id: 'sangue_inimigos',
      name: 'Sangue dos Inimigos',
      type: 'Poder',
      description: 'Enquanto está em fúria, quando faz um acerto crítico ou reduz um inimigo a 0 PV, você recebe um bônus cumulativo de +1 em testes de ataque e rolagens de dano, limitado pelo seu nível, até o fim da cena.',
      prerequisites: [],
    },
    {
      id: 'supersticao',
      name: 'Superstição',
      type: 'Poder',
      description: 'Você odeia magia, o que faz com que seja mais resistente a ela. Você recebe resistência a magia +5.',
      prerequisites: [],
    },
    {
      id: 'totem_espiritual',
      name: 'Totem Espiritual',
      type: 'Poder',
      description: 'Você soma sua Sabedoria no seu total de pontos de mana. Escolha um animal totêmico. Você aprende e pode lançar uma magia definida pelo animal escolhido (atributo-chave Sabedoria) e pode lançá-la mesmo em fúria.',
      prerequisites: [{ type: 'attribute', key: 'sabedoria', value: 1 }, { type: 'level', value: 4 }],
    },
    {
      id: 'vigor_primal',
      name: 'Vigor Primal',
      type: 'Poder',
      description: 'Você pode gastar uma ação de movimento e uma quantidade de PM limitada por sua Constituição. Para cada PM que gastar, você recupera 1d12 pontos de vida.',
      prerequisites: [],
    },
  ],
  bardo: [],
  bucaneiro: [],
  cavaleiro: [],
  clerigo: [],
  druida: [],
  guerreiro: [],
  inventor: [],
  ladino: [],
  lutador: [],
  nobre: [],
  paladino: [],
};
